### PR TITLE
Improving logging message types and error messages

### PR DESCRIPTION
**Pull request by Girishbari**
### Description
Resolve : #6 
Improve log message and tweaked some error message conveying a proper error or suggestion

### Type of change
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update
- [x] refactor 

### Checklist:
- [x] I have read and agree to the [Code of Conduct](https://github.com/reclaimprotocol/.github/blob/main/Code-of-Conduct.md).
- [x] I have signed the [Contributor License Agreement (CLA)](https://github.com/reclaimprotocol/.github/blob/main/CLA.md).
- [x] I have considered the [Security Policy](https://github.com/reclaimprotocol/.github/blob/main/SECURITY.md).
- [x] I have self-reviewed and tested my code.
- [ ] I have updated documentation as needed.
- [x] I agree to the [project's custom license](https://github.com/reclaimprotocol/.github/blob/main/LICENSE).

### CODE REVIEW

**Comment by Kushal7788** [comment]
Some changes are required.

- I'll suggest to go through the changes once more and to make sure the code functionality is not affected when adding logs. 
- We would also like to add more info logs as the user calls the public methods of the sdk to give more context and help user with debugging their application.
- With addition of different log types, we need to provider a way to the user to set the logging level in proofOptions when log are enabled

**Comment by adithyaakrishna** [comment]
@Girishbari Any updates on these?

**Comment by Girishbari** [comment]
yeah been busy with work and ideas to build in the reclaim hackathon, I will update you tomorrow on this although I have a few points to asks
1. how much info should these logs have  while taking note that I don't entirely know the SDK and their public method or if there are docs for these methods already which I can refer to build user-friendly messages
2.  I didn't get the last point, could you please elaborate on that

**Comment by Kushal7788** [comment]
> hi @Kushal7788 found this error while doing local build image **should I change it here or make a new and then push for the change**

@Girishbari this is because you have modified the import function names along with the logs update in this branch. I have added comments for the same. 

This error is not there on main. You can check by taking latest pull from main.

**Comment by Kushal7788** [comment]
> yeah been busy with work and ideas to build in the reclaim hackathon, I will update you tomorrow on this although I have a few points to asks
> 
> 1. how much info should these logs have  while taking note that I don't entirely know the SDK and their public method or if there are docs for these methods already which I can refer to build user-friendly messages
> 2. I didn't get the last point, could you please elaborate on that

To answer your queries

1. You can refer to our [docs](https://docs.reclaimprotocol.org/js) for more information on public methods. I guess you can go through the Reclaim.ts file and directly look at the codebase too. We want some info messages to help users as well as our internal team to understand the errors and help debug them.
2. Currently if you look at the codebase, we support only info logs when logging is enabled. After adding error and warn logs, we need to explicitly set the logging level to either one of the info, warn or error. We want to give that option to the end user to chose among the logging level once they enable logs. If user has not set any logging level then we want to show all the logs from all logging levels. This change need to happen in `init` public method for the SDK. We need to give an additional parameter in options for logging level.

**Pull request closed without merging**
